version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/tms-app
hooks:
  BeforeInstall:
    - location: before_install.sh
      runas: ec2-user
  AfterInstall:
    - location: after_install.sh
      runas: ec2-user
      timeout: 300
